title: Microwave Map PSU
author: Max Loiacono
description: Public Microwaves @ Penn State
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://microwavemap.com" # the base hostname & protocol for your site, e.g. http://example.com
repo_url: "https://github.com/itsmaxymoo/microwavemap"
contrib_email: "contribute@microwavemap.com"

collections:

  locations:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Build settings
timezone: America/New_York
markdown: kramdown
sass:
  style: compressed

exclude:
  - LICENSE.md
  - LICENSE
  - .git*
  - README.md
  - TODO.md
  - "*.sh"
  - .vscode/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - CNAME
